on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: v1.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Discord Post
        shell: bash
        run: |
          # Replace version placeholders in discord.json
          sed "s/\${version}/${{ env.VERSION }}/g" .build/discord.json > discord_payload.json

          # Post to Discord webhook
          curl -H "Content-Type: application/json" \
               -d @discord_payload.json \
               "${{ secrets.DISCORD_WEBHOOK }}"
